Render logged in user profile on root page
jaywink/socialhome pull request #105
Opened 2017-03-04 20:56 UTC by christophehenry

#61

2017-03-04 21:49 UTC, christophehenry commented
Halp! :(

2017-03-04 22:43 UTC, jaywink commented
You need to fix the tests to match the new functionality. Test `test_home_view_rendered_without_root_profile` in https://travis-ci.org/jaywink/socialhome/jobs/207769585#L734 is checking that `home.html` is rendered, but now `profile.html` is rendered, as the test is using a logged in user.

These test adjustments might work? There is a new test and also checking that correct profile is in context. I want to test everything in Socialhome, so you'll need to learn py.test and Django testing.. :)

    @pytest.mark.usefixtures("db")
    class TestRootProfile(object):
        @pytest.mark.usefixtures("client", "settings")
        def test_home_view_rendered_without_root_profile(self, client, settings):
            settings.SOCIALHOME_ROOT_PROFILE = None
            response = client.get("/")
            assert response.templates[0].name == "pages/home.html"
    
        @pytest.mark.usefixtures("admin_client", "settings")
        def test_logged_in_profile_view_rendered_without_root_profile(self, admin_client, settings):
            settings.SOCIALHOME_ROOT_PROFILE = None
            response = admin_client.get("/")
            assert response.templates[0].name == "streams/profile.html"
            assert response.context["profile"].user.username == "admin"
    
        @pytest.mark.usefixtures("client", "admin_client", "settings")
        def test_home_view_rendered_with_root_profile(self, client, admin_client, settings):
            settings.SOCIALHOME_ROOT_PROFILE = "admin"
            # Set admin profile visibility, otherwise it will just redirect to login
            Profile.objects.filter(user__username="admin").update(visibility=Visibility.PUBLIC)
            response = client.get("/")
            assert response.templates[0].name == "streams/profile.html"
            assert response.context["profile"].user.username == "admin"

2017-03-05 14:54 UTC, christophehenry commented
Your adjusment work. Though I do not clearly understand why, yet.

2017-03-05 18:23 UTC, jaywink requested changes

2017-03-05 18:23 UTC, jaywink commented on socialhome/content/tests/test_views.py
> +from types import SimpleNamespace
This import is unused now I think?

2017-03-05 18:23 UTC, christophehenry commented on socialhome/content/tests/test_views.py
> +from types import SimpleNamespace
Yes, it is. I forgot that one.

2017-03-05 18:29 UTC, jaywink approved these changes
Awesome, thanks!

2017-03-05 18:29 UTC, merged