Automatically order new pinned profile content as last (#106)
jaywink/socialhome pull request #107
Opened 2017-03-06 19:58 UTC by christophehenry

2017-03-06 20:26 UTC, jaywink requested changes

2017-03-06 20:26 UTC, jaywink commented on socialhome/content/models.py
> +            if self.pinned:
Hmm this whole `elif author:` is kinda weird, had to dig to find out why it isn't just an `else:`. Anyway, your code should run even if no author. So maybe restructure like:

    if self.pk:
        ...
    else:
        if self.pinned:
            ...
        if author:
            ....

2017-03-06 20:26 UTC, jaywink commented on socialhome/content/models.py
> +                self.order = Content.objects.filter(pinned=True).count() + 1
Your query is wrong. We don't want the count of pinned content, we want the next unused value of `order`. So you need the maximum current value and then `+1`.

2017-03-06 20:49 UTC, pep8speaks commented
Hello @christophehenry! Thanks for updating the PR.

 - There are no PEP8 issues in the file [`socialhome/content/models.py`](https://github.com/christophehenry/socialhome/blob/941aa3c9c3e53d0c3d2c9fa5dd8dda0e3d6d4270/socialhome/content/models.py) !

 - In the file [`socialhome/users/tests/test_views.py`](https://github.com/christophehenry/socialhome/blob/941aa3c9c3e53d0c3d2c9fa5dd8dda0e3d6d4270/socialhome/users/tests/test_views.py), following are the PEP8 issues :

> [Line 153:1](https://github.com/christophehenry/socialhome/blob/941aa3c9c3e53d0c3d2c9fa5dd8dda0e3d6d4270/socialhome/users/tests/test_views.py#L153): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

 - Complete extra results for this file :

> 1       W293 blank line contains whitespace---

2017-03-06 20:57 UTC, christophehenry commented on socialhome/content/models.py
> +                self.order = Content.objects.filter(pinned=True).count() + 1
So `Content.objects.count() + 1`?

2017-03-06 21:04 UTC, jaywink commented on socialhome/content/models.py
> +                self.order = Content.objects.filter(pinned=True).count() + 1
No, that would be the count of objects. You need the largest value. Check https://docs.djangoproject.com/en/1.10/ref/models/querysets/#max

2017-03-06 21:08 UTC, jaywink requested changes

2017-03-06 21:08 UTC, jaywink commented on socialhome/users/tests/test_views.py
> +    def test_content_saved_in_correct_order(self, admin_client, rf):
The feature is in the model, so the test should be in content app `test_models`.

2017-03-06 21:08 UTC, jaywink commented on socialhome/users/tests/test_views.py
> +        assert {pinned_content_1.order, pinned_content_2.order, pinned_content_3.order} == {1, 2, 3}
A Python set is not ordered, so this guarantees only that the elements are in the set: https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset

2017-03-06 22:01 UTC, christophehenry commented
The problem is that it now overrides the `order` parameter set at creation. Like [here](https://github.com/jaywink/socialhome/blob/master/socialhome/users/tests/test_views.py#L79).

2017-03-08 20:05 UTC, jaywink requested changes

2017-03-08 20:05 UTC, jaywink commented on socialhome/content/models.py
> +                max_order = Content.objects.values_list("order").distinct().aggregate(order=Max("order"))["order"]
Way shorter and a lot more performant is:

    Content.objects.aggregate(Max("order"))["order__max"]

But, you're taking *all* content here. We only care about the content of current user. And only pinned content.

Ps pro-tip: use the `python manage.py shell_plus` command to locally play around with these kind of things before writing code.

2017-03-08 20:05 UTC, jaywink commented on socialhome/users/tests/test_models.py
> +    def test_content_saved_in_correct_order(self, admin_client, rf):
This is in `socialhome/users`. It should be in `socialhome/content` app `TestContentModel`.

2017-03-08 20:05 UTC, jaywink commented on socialhome/users/tests/test_views.py
> +from factory import fuzzy
Unused import.

2017-03-08 20:08 UTC, jaywink commented
> The problem is that it now overrides the order parameter set at creation. Like here. I don't know how to solve.

Right, good point. The old tests need to be fixed. Easiest is to after creating the content, update it with the correct order we want, like this:

    content = ContentFactory(author=profile, pinned=True)
    Content.objects.filter(id=content.id).update(order=1)

2017-03-08 20:09 UTC, christophehenry commented on socialhome/content/models.py
> +                max_order = Content.objects.values_list("order").distinct().aggregate(order=Max("order"))["order"]
> Way shorter and a lot more performant is:
> ```
> Content.objects.aggregate(Max("order"))["order__max"]
> ```

I believe you but I don't understand. I remember during my studies my teachers telling me that filtering content like using `DISTINCT` improved queries performance.

2017-03-10 23:18 UTC, jaywink requested changes
One last

2017-03-10 23:18 UTC, jaywink commented on socialhome/users/tests/test_models.py
> +from socialhome.content.models import Content
Unused import.

2017-03-10 23:18 UTC, jaywink commented on socialhome/content/models.py
> +                max_order = Content.objects.aggregate(Max("order"))["order__max"]
OK this is closer, but it still needs to get content only for *user who created this current content*, not all content in the database. You need to add a filter before the aggregate to limit to current authoring user.

2017-03-11 06:49 UTC, christophehenry commented
Done.

2017-03-11 09:21 UTC, jaywink approved these changes
Great, thanks!

2017-03-11 09:21 UTC, merged