Please, Jason, don't juge me :(
jaywink/socialhome pull request #262
Opened 2017-08-19 22:58 UTC by christophehenry

2017-08-19 23:16 UTC, jaywink requested changes
Once tests pass, please rewrite commit message so represents a professional commit showing the reader what the commit is about, thanks ;)

2017-08-19 23:16 UTC, jaywink commented on socialhome/streams/app/components/AuthorBar.vue
> +            if (!this.isUserAuthentificated) {
Should be `isUserAuthenticated`.

2017-08-19 23:16 UTC, jaywink commented on socialhome/streams/app/components/AuthorBar.vue
> +            if (!this.isUserAuthentificated) {
Should be `isUserAuthenticated`.

2017-08-20 00:05 UTC, christophehenry commented
Done

2017-08-20 09:20 UTC, jaywink approved these changes

2017-08-20 09:20 UTC, merged

2017-08-20 09:21 UTC, jaywink commented
Excellent ![](https://media.giphy.com/media/8fen5LSZcHQ5O/giphy.gif)