Add NSFW shield
jaywink/socialhome pull request #330
Opened 2017-10-17 11:08 UTC by christophehenry

Ok, here is my proposition for a NSFW shield:

- hidden

![screenshot-2017-10-17 - socialhome](https://user-images.githubusercontent.com/22097904/31661593-934e3836-b33b-11e7-92c1-19caf554f7c2.png)
- shown

![screenshot-2017-10-17 - socialhome 1](https://user-images.githubusercontent.com/22097904/31661754-1fa1cc26-b33c-11e7-9092-cdf5eeee477e.png)

When hidden, it only shows the tags. BTW, for an unknown reason, the tags `field` of the API does not gives the correct tags. In this example, it's an array containing `3`.

The current implementation solves #111 as the HTML element is not even redered until the user clicks the button to show.

2017-10-17 12:58 UTC, jaywink commented
Awesome! A few notes on the design:

- The tags (when NSFW shield on) should be normally rendered tags (text), not pills. We don't use pills to render tags in the content normally, so it feels weird to have tags rendered in two different ways. They should probably be a link to the tag stream too, like tags normally are. That's kinda optional, though if not, then they shouldn't look like links. If linkifying the tags, make sure to lowercase the whole tag name before making it a link. Otherwise any tag in the system should be "link safe".

- When the shield is off, the "Hide NSFW content" should be more hidden away normal text centered before the rendered content, for example like it is now (though 'content', not 'image', obviously):

![selection_431](https://user-images.githubusercontent.com/1174866/31665527-c20b4860-b351-11e7-87cb-c4379d817bf0.png)

Open to alternatives regarding this, but definitely the box should not be reused for the hiding. The point of the box is to give a clear action to the common thing a user would do with this content. The hiding is more of a secondary action and should be less visible. What do you think?

About the API, yes, the list of tags is currently the ID of the tag, not the name. I think that should probably be changed. You can just pull whatever is in the array for this PR. I can make the API change unless you want to read a bit more into Django REST framework? Basically need to tell it to serialize not the ID but the name of the foreign key relation.

2017-10-17 13:01 UTC, jaywink commented on socialhome/streams/app/components/NsfwShield.vue
> +            return Urls["streams:tag"]({name})
Great, you already did the linkifying. Actually ignore my point about lowercasing - I realized we save all tags lowercase in the `Tag` model when ripping them out of content. So this method is fine.

2017-10-17 14:11 UTC, christophehenry commented
> The tags (when NSFW shield on) should be normally rendered tags (text), not pills. We don't use pills to render tags in the content normally, so it feels weird to have tags rendered in two different ways. 

I was thinking that it's actually a good idea to highlight tags for all posts just below and render tags in post more discretely. It could be easier to read for posts with lots of tags. We could, for instance render tags in text in a slightly lighter grey than text and highlight them as pills.

It would also have another pro: discouraging people to put too many tags in a post to avoid tag spamming which is a pain in diaspora.

> The hiding is more of a secondary action and should be less visible. What do you think?

No strong opposition on that. It's easy to implement and makes sense.

> I can make the API change unless you want to read a bit more into Django REST framework?

Yup. I need to level up on this. I prefer taking care of this.

2017-10-17 18:49 UTC, jaywink commented
We can discuss the highlighting of tags in other than "text with link" in some other future time. Though, personally, I do prefer pure text tag links. It's a standard wherever you look. It makes them stand out but not stand out too much. It doesn't ruin the text flow when reading posts with tags. It doesn't ruin formatting. But always open to mockups which we can discuss :)

However, I think things like that are out of scope of this PR and the tags should have the same rendering we use in content itself.

> It would also have another pro: discouraging people to put too many tags in a post to avoid tag spamming which is a pain in diaspora.

Most content comes from diaspora, or in the future from Mastodon, tho :) Unless Socialhome nodes explode in number into the thousands.

> Yup. I need to level up on this. I prefer taking care of this.

\o/ REST framework is fun and pretty well documented.

2017-10-18 07:58 UTC, christophehenry commented
Indeed, you're right, styling out of scope. Let's stick to pure text links.

2017-10-18 11:11 UTC, christophehenry commented
I'm having troubles testing things. Running `py.test`, I get:

```
Got an error creating the test database: permission denied to create database

Got an error recreating the test database: database "test_socialhome" does not exist
```

2017-10-18 11:19 UTC, christophehenry commented on socialhome/content/tests/test_serializers.py
> +        self.assertEquals(serializer.get_tags(self.content), [])
![Halp!](https://user-images.githubusercontent.com/22097904/31716173-e6b3579c-b406-11e7-9911-4b4a03c19b33.jpg)

2017-10-18 12:47 UTC, jaywink commented
> Got an error creating the test database: permission denied to create database

You need to give the user rights to create databases, for example:

    sudo -u postgres psql -c "ALTER USER socialhome CREATEDB;"

Seems this is missing from the development docs, sorry, let me know if it was the issue and will add!

2017-10-21 13:20 UTC, jaywink commented on socialhome/content/tests/test_serializers.py
> +        self.content.update(tags=[tag])
This should be `self.content.tags.add(tag)`.

2017-10-21 13:37 UTC, jaywink commented on socialhome/content/serializers.py
> +    def get_tags(self, obj):
While this works, it's inefficient. REST framework has a thing to do this, it's the [SlugRelatedField](http://www.django-rest-framework.org/api-guide/relations/#slugrelatedfield). Using that exactly as the example there (with `read_only` and `many`, field name `name`) should work nicely and be well optimized.

2017-10-21 17:07 UTC, jaywink requested changes
A few things to fix re serializer.

Also, please add a changelog entry to the "Changed" section in the current unreleased version. Something like:

    **Breaking change**. Content API now returns Content list of tags as *name of tag*, not ID as before. The name does not contain the character "#".

2017-10-21 17:07 UTC, jaywink commented on socialhome/content/serializers.py
> +    tags = SlugRelatedField(many=True, read_only=True, slug_field="tags")
`slug_field` should be `name`.

2017-10-21 17:07 UTC, jaywink commented on socialhome/content/serializers.py
> +    def get_tags(self, obj):
This method is not necessary when using `SlugRelatedField`.

2017-10-21 17:07 UTC, jaywink commented on socialhome/content/tests/test_serializers.py
> +        self.assertEquals(serializer.get_tags(self.content), [])
These tests should now check the serialized content object and what `tags` list contains. You will find the list as `serializer.data["tags"]`.

2017-10-21 17:19 UTC, jaywink requested changes
One more comment. Also, that changelog entry would be nice 👍  Saves an extra follow up commit.

2017-10-21 17:19 UTC, jaywink commented on socialhome/content/serializers.py
> +from socialhome.content.models import Content, Tag
Tag import is unnecessary.

2017-10-22 16:11 UTC, jaywink commented on docs/changelog.rst
> +* **Breaking change**
The changelog is a list inside each header, but I'll fix this in a separate commit, noticed one other thing to add too 👍

2017-10-22 16:11 UTC, jaywink approved these changes

2017-10-22 16:11 UTC, jaywink commented
Thanks! <3

2017-10-22 16:11 UTC, merged