Make profile image url absolute
jaywink/socialhome pull request #348
Opened 2017-10-28 21:51 UTC by amirkarimi

https://github.com/jaywink/socialhome/issues/327

2017-10-29 08:59 UTC, jaywink requested changes
Thanks for working on this! One change request, then good to go!

2017-10-29 08:59 UTC, jaywink commented on socialhome/users/models.py
> +    def absolute_remote_url(remote_profile, image_name):
Could the signature be `absolute_image_url(profile, image_name)`? Reason: while we're using this for remote profile parsing, the functionality in the method doesn't actually have anything strictly to do with remote profiles. But it does have everything to do with image url's, so calling it `absolute_image_url` would make it easier to see right from the name what it does. With the current name my first thought is that this returns "an absolute url for the remote profile itself".

Also, a short docstring would be nice, just to indicate what it does (= returns absolute version of image ulr of given size).

2017-10-29 19:55 UTC, jaywink approved these changes

2017-10-29 19:56 UTC, jaywink commented
Perfect! Thanks for this <3 Did you also want to work on removing the `safer_` method usages (requires also doing a data migration for any profile image urls that are relative) or shall I log it as a follow-up issue?

2017-10-29 19:56 UTC, merged

2017-10-29 20:27 UTC, amirkarimi commented
@jaywink I would like to work on it but as I might be a little bit busy, I think it's better to create another issue. I'll pick it up ASAP.

2017-11-19 17:48 UTC, jaywink commented
@amirkarimi logged #374 , sorry forgot about this for a while. If you're interested in tackling it at some point. Thanks again for your contribution!